//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jalkahoitola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tyontekija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tyontekija()
        {
            this.Ajanvaraus = new HashSet<Ajanvaraus>();
        }
    
        public int TyontekijaID { get; set; }
        public string Sukunimi { get; set; }
        public string Etunimi { get; set; }
        public string Puhnro { get; set; }
        public string Sposti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ajanvaraus> Ajanvaraus { get; set; }
    }
}
